### ISSUE TITLE
问个字符串长度的问题

### ISSUE THREAD

**Issue by alsotang** [joyeecheung/md5#1]
我看 readme 里面有下述代码：

```
md5.update(reinterpret_cast<char*>(&data), sizeof(data));
```

是不是因为 data 是 1234，刚好无论是 int 还是 char\* 都是 4 个长度，所以输出了正确的 md5 值。

如果 data 的值是 1 的话呢？
那么 data 作为字符串的长度是 1，作为 int 的长度还是 4。
在这个地方，我们不是应该取 data 的字符串形式的长度吗？

**Comment by joyeecheung** [comment]
如果是"1"的话，那么就是一个1byte的字符串，内容是“1”的ASCII码。如果是1的话，就是一个4byte的整数。两者是完全不同的数据。md5("1234")和md5(1234)本来就不应该得到一样的结果。

**Comment by alsotang** [comment]
原来 md5("1234")和md5(1234) 不是一个意思啊..我平时用脚本语言都是主动传递字符串给 md5 函数的，没有考虑到这个问题，抱歉。
